create table tblStudent(RollNumber int GENERATED AS IDENTITY primary key,
FullName nvarchar2(50), Address nvarchar2(200), ClassName nvarchar2(100))

insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n V?n Ti?n',N'Sóc S?n - Hà N?i','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n Anh ??c',N'Ba Vì - Hà N?i','C1406L')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n V?n Thành',N'?ông Anh - Hà N?i','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr?n ??c Nam',N'Hai Bà Tr?ng - Hà N?i','C1406L')
insert into tblStudent(FullName,Address,ClassName) values (N'Ngô Ng?c Lan',N'Sóc S?n - Hà N?i','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n Tr?n Qu?nh',N'?ông Anh - Hà N?i','C1101L')
insert into tblStudent(FullName,Address,ClassName) values (N'?inh Ng?c Sinh',N'Na Rì - B?c K?n','C1406L')
insert into tblStudent(FullName,Address,ClassName) values (N'Lê Thành Tâm',N'Ngân S?n - B?c K?n','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n V?n Quy?t',N'?ông Anh - Hà N?i','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr??ng V?n ?ông',N'Thanh S?n - Phú Th?','C1101L')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n V?n Siêu',N'Thanh S?n - Phú Th?','C1507G')
insert into tblStudent(FullName,Address,ClassName) values (N'Bùi ??c H?u',N'Nga S?n - Thanh Hóa','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Lê Thành Nam',N'Hà Trung - Thanh Hóa','C1507G')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n V?n Hào',N'Cao Phong - Hòa Bình','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Ph?m V?n Quân',N'H?u L?c - Thanh Hóa','C1507G')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr?n Th? Huy?n',N'Ý Yên - Nam ??nh','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Ngô Ti?n D?ng',N'TP. Nam ??nh - Nam ??nh','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n V?n D?ng',N'Vi?t Trì - Phú Th?','C1507G')
insert into tblStudent(FullName,Address,ClassName) values (N'Bùi ??c Nam',N'??ng H? - Thái Nguyên','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr?n Thanh Huy?n',N'L?c S?n - Hòa Bình','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n Ng?c Lan',N'Tân L?c - Hòa Bình','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Lê Ng?c Lân',N'Gia Vi?n - Ninh Bình','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Ph?m ??c M?nh',N'H??ng Khê - Hà T?nh','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Châu Tinh Trì',N'TX.??ng H?i - Qu?ng Bình','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Ph?m Bá Quân',N'Ý Yên - Nam ??nh','C1101L')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr?n S? Thành',N'Nga S?n - Thanh Hóa','C1508H')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n Nam Ti?n',N'S?m S?n - Thanh Hóa','C1507G')
insert into tblStudent(FullName,Address,ClassName) values (N'?inh Bá L?c',N'L?c Th?y - Hòa Bình','C1606M')
insert into tblStudent(FullName,Address,ClassName) values (N'Bùi Ng?c Lan',N'Ng?c L?c - Thanh Hóa','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Ph?m Tiên Sinh',N'?ông Anh - Hà N?i','C1011H')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n Siêu Qu?n',N'Gia Lâm - Hà N?i','C0909G')
insert into tblStudent(FullName,Address,ClassName) values (N'H? H?u ?ôn',N'Sóc S?n - Hà N?i','C1406L')
insert into tblStudent(FullName,Address,ClassName) values (N'Ng?c V?n Hoàng',N'?ông Anh - Hà N?i','C1603M')
insert into tblStudent(FullName,Address,ClassName) values (N'Nguy?n S? T?t',N'C?u Gi?y - Hà N?i','C1606M')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr?n Nam S?n',N'Hà ?ông - Hà N?i','C1507G')
insert into tblStudent(FullName,Address,ClassName) values (N'Tr??ng Bá Nam',N'Sóc S?n - Hà N?i','C1606M')

select * from tblStudent
